<?php

namespace ContainerXXihalW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DWMDI0Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.dWMDI0_' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.dWMDI0_'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'batimentRepository' => ['privates', 'App\\Repository\\BatimentRepository', 'getBatimentRepositoryService', true],
        ], [
            'batimentRepository' => 'App\\Repository\\BatimentRepository',
        ]);
    }
}
