<?php

namespace ContainerXXihalW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBatimentService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.0D9EsMK.App\Entity\Batiment' shared service.
     *
     * @return \App\Entity\Batiment
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.0D9EsMK": it references class "App\\Entity\\Batiment" but no such service exists.');
    }
}
