<?php

namespace ContainerX8wVscM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Og_NrYuService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.og.nrYu' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.og.nrYu'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'roomRepository' => ['privates', 'App\\Repository\\ChambreRepository', 'getChambreRepositoryService', true],
        ], [
            'roomRepository' => 'App\\Repository\\ChambreRepository',
        ]);
    }
}
