<?php

namespace ContainerX8wVscM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CEHkIService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.cE_hk_I' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.cE_hk_I'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\BatimentController::afficher' => ['privates', '.service_locator.dWMDI0_', 'get_ServiceLocator_DWMDI0Service', true],
            'App\\Controller\\BatimentController::read' => ['privates', '.service_locator.0D9EsMK', 'get_ServiceLocator_0D9EsMKService', true],
            'App\\Controller\\ChambreController::afficher' => ['privates', '.service_locator.iPOOhYL', 'get_ServiceLocator_IPOOhYLService', true],
            'App\\Controller\\ChambreController::create' => ['privates', '.service_locator.og.nrYu', 'get_ServiceLocator_Og_NrYuService', true],
            'App\\Controller\\EtudiantController::afficher' => ['privates', '.service_locator.9XwlsRB', 'get_ServiceLocator_9XwlsRBService', true],
            'App\\Controller\\EtudiantController::index' => ['privates', '.service_locator.unHTEds', 'get_ServiceLocator_UnHTEdsService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'App\\Controller\\BatimentController:afficher' => ['privates', '.service_locator.dWMDI0_', 'get_ServiceLocator_DWMDI0Service', true],
            'App\\Controller\\BatimentController:read' => ['privates', '.service_locator.0D9EsMK', 'get_ServiceLocator_0D9EsMKService', true],
            'App\\Controller\\ChambreController:afficher' => ['privates', '.service_locator.iPOOhYL', 'get_ServiceLocator_IPOOhYLService', true],
            'App\\Controller\\ChambreController:create' => ['privates', '.service_locator.og.nrYu', 'get_ServiceLocator_Og_NrYuService', true],
            'App\\Controller\\EtudiantController:afficher' => ['privates', '.service_locator.9XwlsRB', 'get_ServiceLocator_9XwlsRBService', true],
            'App\\Controller\\EtudiantController:index' => ['privates', '.service_locator.unHTEds', 'get_ServiceLocator_UnHTEdsService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
        ], [
            'App\\Controller\\BatimentController::afficher' => '?',
            'App\\Controller\\BatimentController::read' => '?',
            'App\\Controller\\ChambreController::afficher' => '?',
            'App\\Controller\\ChambreController::create' => '?',
            'App\\Controller\\EtudiantController::afficher' => '?',
            'App\\Controller\\EtudiantController::index' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\BatimentController:afficher' => '?',
            'App\\Controller\\BatimentController:read' => '?',
            'App\\Controller\\ChambreController:afficher' => '?',
            'App\\Controller\\ChambreController:create' => '?',
            'App\\Controller\\EtudiantController:afficher' => '?',
            'App\\Controller\\EtudiantController:index' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
