<?php

namespace ContainerX8wVscM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_9XwlsRBService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9XwlsRB' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9XwlsRB'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'etudiantRepository' => ['privates', 'App\\Repository\\EtudiantRepository', 'getEtudiantRepositoryService', true],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
        ], [
            'etudiantRepository' => 'App\\Repository\\EtudiantRepository',
            'paginator' => '?',
        ]);
    }
}
