<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSQnVuCO\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSQnVuCO/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSQnVuCO.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSQnVuCO\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSQnVuCO\App_KernelDevDebugContainer([
    'container.build_hash' => 'SQnVuCO',
    'container.build_id' => '5fbd4be2',
    'container.build_time' => 1594011443,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSQnVuCO');
