<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXXihalW\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXXihalW/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXXihalW.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXXihalW\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXXihalW\App_KernelDevDebugContainer([
    'container.build_hash' => 'XXihalW',
    'container.build_id' => '23e627a2',
    'container.build_time' => 1594324772,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXXihalW');
