<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2kUYK73\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2kUYK73/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container2kUYK73.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container2kUYK73\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container2kUYK73\App_KernelDevDebugContainer([
    'container.build_hash' => '2kUYK73',
    'container.build_id' => '7132c602',
    'container.build_time' => 1593788781,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2kUYK73');
