<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    'batiment_afficher' => [[], ['_controller' => 'App\\Controller\\BatimentController::afficher'], [], [['text', '/batiment/afficher']], [], []],
    'batiment_read' => [['id'], ['_controller' => 'App\\Controller\\BatimentController::read'], ['id' => '[0-9]+'], [['variable', '/', '[0-9]+', 'id', true], ['text', '/batiment']], [], []],
    'batiment' => [[], ['_controller' => 'App\\Controller\\BatimentController::index'], [], [['text', '/batiment']], [], []],
    'chambre_index' => [[], ['_controller' => 'App\\Controller\\ChambreController::index'], [], [['text', '/chambre']], [], []],
    'chambre_create' => [[], ['_controller' => 'App\\Controller\\ChambreController::create'], [], [['text', '/chambre/create']], [], []],
    'chambre_afficher' => [[], ['_controller' => 'App\\Controller\\ChambreController::afficher'], [], [['text', '/chambre/afficher']], [], []],
    'chambre_update' => [['id'], ['_controller' => 'App\\Controller\\ChambreController::update'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/chambre/update']], [], []],
    'chambre_delete' => [['id'], ['_controller' => 'App\\Controller\\ChambreController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/chambre/delete']], [], []],
    'etudiant_complet' => [[], ['_controller' => 'App\\Controller\\EtudiantCompletController::index'], [], [['text', '/etudiant/complet']], [], []],
    'etudiant_afficher' => [[], ['_controller' => 'App\\Controller\\EtudiantController::afficher'], [], [['text', '/etudiant']], [], []],
    'etudiant_update' => [['id'], ['_controller' => 'App\\Controller\\EtudiantController::update'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/etudiant/update']], [], []],
    'etudiant_delete' => [['id'], ['_controller' => 'App\\Controller\\EtudiantController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/etudiant/delete']], [], []],
    'etudiant_detail' => [['id'], ['_controller' => 'App\\Controller\\EtudiantController::detail'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/etudiant/detail']], [], []],
    'etudiant' => [[], ['_controller' => 'App\\Controller\\EtudiantController::index'], [], [['text', '/']], [], []],
];
